name: Check version increment

on: 
  pull_request:
    branches:
      - master

jobs:
  check-version-increment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Print tags
        run: git tag -l
      - name: Check if version tag exists
        run: git tag -l | grep -v ${{ steps.package-version.outputs.current-version }}
