name: Check version increment

on: 
  pull_request:
    branches:
      - master

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Check if version tag exists
        run: tag=$(git tag -l ${{ steps.package-version.outputs.current-version }}) && test v$tag != v${{ steps.package-version.outputs.current-version }}
